### ISSUE TITLE
Script writing for Zuri's first presentation

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#106]

**Comment by Guzi-goz** [comment]
Done!

**Comment by SerahN** [comment]
I worked alongside @Guzi-goz in developing the script that was used by the presenters in the first presentation video. This script was a major contribution towards the team's excellent performance. 

Link to script: [https://docs.google.com/document/d/10VD_HXvWZkge0fFsT2DA6qnkNkxLG8vV/edit?usp=sharing&ouid=103045370830872132486&rtpof=true&sd=true](url)
