### ISSUE TITLE
Script writing for Zuri's final presentation

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#107]

**Comment by SerahN** [comment]
I am working alongside Maureen Chukwurah @Guzi-goz  in developing the script that will be used by the presenters in the final presentation video.

**Comment by Guzi-goz** [comment]
Zuri does not only have tech sis, but script writers too. Collaborating with Serah Nwoke @SerahN on writing the script for our final and first presentation was all shades of awesome!

**Comment by SerahN** [comment]
This task is completed by Maureen Chukwurah @Guzi-goz and myself, and can be found here: [https://docs.google.com/document/d/1w2lRIW-1HkEvwhWvyKlM4ly4SHHUzNIY/edit?usp=sharing&ouid=103045370830872132486&rtpof=true&sd=true](url)
