### ISSUE TITLE
Developers to be interviewed by designers

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#139]

**Comment by SerahN** [comment]
I was interviewed by a designer on the team, Prosper Oke @Prospernias , during the design research.

**Comment by WakHerv7** [comment]
I was interviewed by one of our designers in team 64, Bukunmi sonibare @cutebukumi, during the design research.

**Comment by blessingarizona** [comment]
I was interviewed by one of the designers in my team, Temilade Mogaji @softlife12, during the design research.
