### ISSUE TITLE
your site is now live 

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/Team-64_Favicon-Gen#141]
http://zuricongen.zurifordummies.com/
@SerahN
<img width="1440" alt="Screenshot 2022-08-14 at 6 15 29 AM" src="https://user-images.githubusercontent.com/48237269/184523551-858b48db-320d-4e40-96d6-58d36c0c8c4c.png">

**Comment by WakHerv7** [comment]
Can you explain better please ?

Oh I think I know. Please Don't remove the STATICFILES_DIRS, instead create an empty static/ directory in the root alongside assets/ and main/
