### ISSUE TITLE
Implement Texticons page

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#16]

**Comment by AmakaSilas** [comment]
good job

**Comment by SerahN** [comment]
I worked on the Texticons page (frontend) following the design created by the designers on the team. 

Branch: [https://github.com/zuri-training/Team-64_Favicon-Gen/tree/TexticonsPage](url)
PR: [https://github.com/zuri-training/Team-64_Favicon-Gen/pull/87](url)
