### ISSUE TITLE
Research plan and interview

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#19]

**Comment by SerahN** [comment]
[https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=95%3A713](url)

**Comment by midealamutu** [comment]
Completed!

**Comment by kobimdi** [comment]
Done

**Comment by Prospernias** [comment]
Done

**Comment by softlife12** [comment]
Task completed!

**Comment by Bola001** [comment]
Done

**Comment by Designbybecca** [comment]
Task completed!

**Comment by Prospernias** [comment]
Done

**Comment by Trippyog44** [comment]
Task completed!

**Comment by mamoblack** [comment]
completed.... I sent out survey forms and interviewed developers outside our team and the response was quite impressive. Had to interview a software developer outside the platform as well.
