### ISSUE TITLE
Research objective and problem

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#20]

**Comment by SerahN** [comment]
[https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=95%3A713](url)

**Comment by midealamutu** [comment]
Completed!

**Comment by Bola001** [comment]
Done

**Comment by mamoblack** [comment]
carried out the necessary research objective aimed at understanding how favicon gen works and created a problem statement then the team came up with a solution aligned to users journey and experience.
