### ISSUE TITLE
Idea prioritization matrix

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#25]

**Comment by SerahN** [comment]
[https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=95%3A713](url)

**Comment by Bola001** [comment]
Done.
From the pain points listed by some of the team designers and I, I came up with the idea priotization matrix on the figjam file.
The link to the figjam file : https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=0%3A1
