### ISSUE TITLE
User story

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#26]

**Comment by SerahN** [comment]
[https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=95%3A713](url)

**Comment by Designbybecca** [comment]
Task completed!

**Comment by Prospernias** [comment]
Done

**Comment by Bola001** [comment]
Done.
I came up with some of the user stories while making reference to the user persona.
Link to the figjam file : https://www.figma.com/file/2P8rcupisqFHMPfaX5TeDl/Team-64_Favicon_gen?node-id=0%3A1

**Comment by Trippyog44** [comment]
Task completed
