### ISSUE TITLE
Texticons page (Desktop & tablet- high fidelity)

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#70]

**Comment by Bola001** [comment]
Thanks boss

**Comment by Bola001** [comment]
Done. 
I created the High fidelity Desktop and tablet page by selecting the appropriate colour scheme from the style guide. The design was then used to create the mobile frame.
Link to the design file : https://www.figma.com/file/Q6kNdChpgQzLfjIKwSl2Ok/Team-64_Favicon_gen
