### ISSUE TITLE
Implement Saved Drafts/ Downloads page

### ISSUE THREAD

**Issue by SerahN** [zuri-training/Team-64_Favicon-Gen#71]

**Comment by jolomi212** [comment]
I worked on the frontend for the saved drafts page, by implementing the designs with HTML, CSS and javascript. Fully responsive as well.
 Also, the branch which contained the commits for this task https://github.com/zuri-training/Team-64_Favicon-Gen/tree/saved_favicons
 the latest commit: https://github.com/zuri-training/Team-64_Favicon-Gen/commit/1b90e3cc61ccb9c5969a435c389e953d8995d02e
